export default [
  {
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4.5,
  },
  {
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4.5,
  },
  {
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4.5,
  },
  {
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4.5,
  },
  {
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4.5,
  },
  {
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
  {
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 5,
  },
  {
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", 'Channing Tatum'],
    availability: ['Disney+', 'Amazon US'],
    alt_title: ['-'],
    rating: 4,
  },
];
