export default [
  {
    id: 1,
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 2,
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 3,
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 5,
  },
  {
    id: 4,
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 5,
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 5,
  },
  {
    id: 6,
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 7,
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 8,
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 9,
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 5,
  },
  {
    id: 10,
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 11,
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 5,
  },
  {
    id: 12,
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 13,
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 14,
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 15,
    img: "/posters/alien_romulus.jpg",
    year: 2024,
    title: "Alien: Romulus",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Thriller"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 5,
  },
  {
    id: 16,
    img: "/posters/twisters.jpg",
    year: 2024,
    title: "Twisters",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 17,
    img: "/posters/thedarkrises.jpg",
    year: 2024,
    title: "Batman: The Dark Knight Rises",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 5,
  },
  {
    id: 18,
    img: "/posters/the_crow.jpg",
    year: 2024,
    title: "The Crow",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Thriller", "Horror"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 19,
    img: "/posters/interstellar.jpg",
    year: 2014,
    title: "Interstellar",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Sci-Fi", "Adventure"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  },
  {
    id: 20,
    img: "/posters/deadpool_wolverine.jpg",
    year: 2024,
    title: "Deadpool & Wolverine",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    genre: ["Action", "Comedy"],
    actor: ["Ryan Reynolds", "Hugh Jackman", "Channing Tatum"],
    availability: ["Disney+", "Amazon US"],
    alt_title: ["-"],
    rating: 4,
  }
]